import { Initiative } from './types';

export const mockInitiatives: Initiative[] = [
  {
    id: '1',
    processNumber: 'PI-001',
    name: 'Customer to Transformer',
    description: 'Improve the process of mapping customers to their respective transformers for better service management',
    status: 'in progress',
    completenessRate: 65,
    startDate: '2024-01-15',
    completionDate: '2024-06-30',
    tasks: [
      {
        id: 't1',
        name: 'Data Collection',
        description: 'Gather existing customer-transformer mappings',
        status: 'completed',
        deadline: '2024-02-15',
        weight: 20,
        percentCompleted: 100,
        files: [
          { id: 'f1', name: 'data_collection_plan.pdf', size: 245000, uploadDate: '2024-01-10', type: 'application/pdf' },
          { id: 'f2', name: 'legacy_system_export.xlsx', size: 1024000, uploadDate: '2024-01-15', type: 'application/vnd.ms-excel' },
        ],
      },
      {
        id: 't2',
        name: 'System Integration',
        description: 'Integrate mapping system with GIS',
        status: 'in progress',
        deadline: '2024-04-30',
        weight: 40,
        percentCompleted: 60,
        files: [
          { id: 'f3', name: 'integration_specs.docx', size: 156000, uploadDate: '2024-02-01', type: 'application/msword' },
        ],
      },
      {
        id: 't3',
        name: 'Testing & Validation',
        description: 'Validate accuracy of mappings',
        status: 'not started',
        deadline: '2024-06-15',
        weight: 40,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '2',
    processNumber: 'PI-002',
    name: 'Conductor Standardization',
    description: 'Standardize conductor types and specifications across the network',
    status: 'in progress',
    completenessRate: 45,
    startDate: '2024-02-01',
    completionDate: '2024-08-31',
    tasks: [
      {
        id: 't4',
        name: 'Inventory Assessment',
        description: 'Catalog all existing conductor types',
        status: 'completed',
        deadline: '2024-03-01',
        weight: 25,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't5',
        name: 'Standard Development',
        description: 'Define standard conductor specifications',
        status: 'in progress',
        deadline: '2024-05-15',
        weight: 35,
        percentCompleted: 50,
        files: [],
      },
      {
        id: 't6',
        name: 'Implementation Plan',
        description: 'Create rollout plan for standardization',
        status: 'not started',
        deadline: '2024-07-31',
        weight: 40,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '3',
    processNumber: 'PI-003',
    name: 'Tie Points Data Collection',
    description: 'Comprehensive data collection of all network tie points',
    status: 'planned',
    completenessRate: 15,
    startDate: '2024-03-01',
    completionDate: '2024-09-30',
    tasks: [
      {
        id: 't7',
        name: 'Field Survey Planning',
        description: 'Plan field survey routes and schedule',
        status: 'in progress',
        deadline: '2024-04-01',
        weight: 30,
        percentCompleted: 50,
        files: [],
      },
      {
        id: 't8',
        name: 'Data Collection',
        description: 'Execute field surveys',
        status: 'not started',
        deadline: '2024-07-31',
        weight: 50,
        percentCompleted: 0,
        files: [],
      },
      {
        id: 't9',
        name: 'Data Entry & Validation',
        description: 'Enter and validate collected data',
        status: 'not started',
        deadline: '2024-09-15',
        weight: 20,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '4',
    processNumber: 'PI-004',
    name: 'Load Flow Interruption Devices',
    description: 'Optimize placement and operation of load flow interruption devices',
    status: 'in progress',
    completenessRate: 72,
    startDate: '2024-01-10',
    completionDate: '2024-05-31',
    tasks: [
      {
        id: 't10',
        name: 'Network Analysis',
        description: 'Analyze current device placement',
        status: 'completed',
        deadline: '2024-02-28',
        weight: 30,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't11',
        name: 'Optimization Model',
        description: 'Develop optimization algorithm',
        status: 'completed',
        deadline: '2024-04-15',
        weight: 40,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't12',
        name: 'Implementation',
        description: 'Deploy optimized configuration',
        status: 'in progress',
        deadline: '2024-05-30',
        weight: 30,
        percentCompleted: 40,
        files: [],
      },
    ],
  },
  {
    id: '5',
    processNumber: 'PI-005',
    name: 'Phase Designation',
    description: 'Standardize phase designation across the distribution network',
    status: 'on hold',
    completenessRate: 30,
    startDate: '2024-02-15',
    completionDate: '2024-10-31',
    tasks: [
      {
        id: 't13',
        name: 'Current State Analysis',
        description: 'Document existing phase designations',
        status: 'completed',
        deadline: '2024-03-31',
        weight: 25,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't14',
        name: 'Standard Definition',
        description: 'Define phase designation standards',
        status: 'in progress',
        deadline: '2024-06-30',
        weight: 35,
        percentCompleted: 20,
        files: [],
      },
      {
        id: 't15',
        name: 'System Updates',
        description: 'Update systems with new standards',
        status: 'not started',
        deadline: '2024-10-15',
        weight: 40,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '6',
    processNumber: 'PI-006',
    name: 'Phase Orientation',
    description: 'Ensure correct phase orientation throughout the network',
    status: 'in progress',
    completenessRate: 55,
    startDate: '2024-01-20',
    completionDate: '2024-07-31',
    tasks: [
      {
        id: 't16',
        name: 'Orientation Survey',
        description: 'Survey current phase orientations',
        status: 'completed',
        deadline: '2024-03-15',
        weight: 30,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't17',
        name: 'Correction Plan',
        description: 'Develop correction plan for misaligned phases',
        status: 'in progress',
        deadline: '2024-05-31',
        weight: 40,
        percentCompleted: 65,
        files: [],
      },
      {
        id: 't18',
        name: 'Field Corrections',
        description: 'Execute field corrections',
        status: 'not started',
        deadline: '2024-07-30',
        weight: 30,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '7',
    processNumber: 'PI-007',
    name: 'Asset Tagging System',
    description: 'Implement comprehensive asset tagging system',
    status: 'completed',
    completenessRate: 100,
    startDate: '2023-09-01',
    completionDate: '2024-02-28',
    tasks: [
      {
        id: 't19',
        name: 'Tag Design',
        description: 'Design tag format and specifications',
        status: 'completed',
        deadline: '2023-10-15',
        weight: 20,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't20',
        name: 'System Development',
        description: 'Develop tracking system',
        status: 'completed',
        deadline: '2023-12-31',
        weight: 40,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't21',
        name: 'Deployment',
        description: 'Deploy tags across network',
        status: 'completed',
        deadline: '2024-02-28',
        weight: 40,
        percentCompleted: 100,
        files: [],
      },
    ],
  },
  {
    id: '8',
    processNumber: 'PI-008',
    name: 'Meter Data Management',
    description: 'Improve meter data collection and management processes',
    status: 'in progress',
    completenessRate: 40,
    startDate: '2024-02-01',
    completionDate: '2024-08-31',
    tasks: [
      {
        id: 't22',
        name: 'System Requirements',
        description: 'Define MDM system requirements',
        status: 'completed',
        deadline: '2024-03-15',
        weight: 25,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't23',
        name: 'Vendor Selection',
        description: 'Select MDM system vendor',
        status: 'in progress',
        deadline: '2024-05-31',
        weight: 35,
        percentCompleted: 50,
        files: [],
      },
      {
        id: 't24',
        name: 'Implementation',
        description: 'Implement MDM system',
        status: 'not started',
        deadline: '2024-08-30',
        weight: 40,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '9',
    processNumber: 'PI-009',
    name: 'Outage Management Optimization',
    description: 'Optimize outage detection and response procedures',
    status: 'planned',
    completenessRate: 20,
    startDate: '2024-03-15',
    completionDate: '2024-10-31',
    tasks: [
      {
        id: 't25',
        name: 'Process Review',
        description: 'Review current outage management process',
        status: 'in progress',
        deadline: '2024-04-30',
        weight: 30,
        percentCompleted: 65,
        files: [],
      },
      {
        id: 't26',
        name: 'System Enhancement',
        description: 'Enhance outage management system',
        status: 'not started',
        deadline: '2024-08-31',
        weight: 50,
        percentCompleted: 0,
        files: [],
      },
      {
        id: 't27',
        name: 'Training',
        description: 'Train staff on new procedures',
        status: 'not started',
        deadline: '2024-10-15',
        weight: 20,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '10',
    processNumber: 'PI-010',
    name: 'Vegetation Management',
    description: 'Improve vegetation management along power lines',
    status: 'in progress',
    completenessRate: 58,
    startDate: '2024-01-05',
    completionDate: '2024-12-31',
    tasks: [
      {
        id: 't28',
        name: 'Risk Assessment',
        description: 'Assess vegetation risks along corridors',
        status: 'completed',
        deadline: '2024-03-01',
        weight: 25,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't29',
        name: 'Trimming Schedule',
        description: 'Develop optimized trimming schedule',
        status: 'in progress',
        deadline: '2024-06-30',
        weight: 35,
        percentCompleted: 70,
        files: [],
      },
      {
        id: 't30',
        name: 'Execution',
        description: 'Execute trimming program',
        status: 'in progress',
        deadline: '2024-12-15',
        weight: 40,
        percentCompleted: 35,
        files: [],
      },
    ],
  },
  {
    id: '11',
    processNumber: 'PI-011',
    name: 'Pole Inspection Program',
    description: 'Systematic pole inspection and maintenance program',
    status: 'in progress',
    completenessRate: 48,
    startDate: '2024-01-15',
    completionDate: '2024-11-30',
    tasks: [
      {
        id: 't31',
        name: 'Inspection Protocol',
        description: 'Develop inspection standards',
        status: 'completed',
        deadline: '2024-02-28',
        weight: 20,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't32',
        name: 'Field Inspections',
        description: 'Conduct pole inspections',
        status: 'in progress',
        deadline: '2024-09-30',
        weight: 60,
        percentCompleted: 45,
        files: [],
      },
      {
        id: 't33',
        name: 'Remediation',
        description: 'Address identified issues',
        status: 'not started',
        deadline: '2024-11-30',
        weight: 20,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '12',
    processNumber: 'PI-012',
    name: 'Transformer Load Balancing',
    description: 'Balance loads across transformers for optimal performance',
    status: 'planned',
    completenessRate: 10,
    startDate: '2024-04-01',
    completionDate: '2024-12-31',
    tasks: [
      {
        id: 't34',
        name: 'Load Analysis',
        description: 'Analyze current transformer loads',
        status: 'in progress',
        deadline: '2024-05-31',
        weight: 35,
        percentCompleted: 30,
        files: [],
      },
      {
        id: 't35',
        name: 'Balancing Strategy',
        description: 'Develop load balancing strategy',
        status: 'not started',
        deadline: '2024-09-30',
        weight: 40,
        percentCompleted: 0,
        files: [],
      },
      {
        id: 't36',
        name: 'Implementation',
        description: 'Implement load balancing changes',
        status: 'not started',
        deadline: '2024-12-15',
        weight: 25,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '13',
    processNumber: 'PI-013',
    name: 'Emergency Response Planning',
    description: 'Enhance emergency response capabilities',
    status: 'in progress',
    completenessRate: 75,
    startDate: '2023-11-01',
    completionDate: '2024-04-30',
    tasks: [
      {
        id: 't37',
        name: 'Risk Assessment',
        description: 'Identify emergency scenarios',
        status: 'completed',
        deadline: '2024-01-15',
        weight: 25,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't38',
        name: 'Response Protocols',
        description: 'Develop response protocols',
        status: 'completed',
        deadline: '2024-03-01',
        weight: 40,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't39',
        name: 'Training Program',
        description: 'Train response teams',
        status: 'in progress',
        deadline: '2024-04-30',
        weight: 35,
        percentCompleted: 50,
        files: [],
      },
    ],
  },
  {
    id: '14',
    processNumber: 'PI-014',
    name: 'Network Redundancy Analysis',
    description: 'Analyze and improve network redundancy',
    status: 'planned',
    completenessRate: 5,
    startDate: '2024-04-15',
    completionDate: '2024-12-31',
    tasks: [
      {
        id: 't40',
        name: 'Current State Assessment',
        description: 'Assess existing redundancy measures',
        status: 'in progress',
        deadline: '2024-06-30',
        weight: 40,
        percentCompleted: 15,
        files: [],
      },
      {
        id: 't41',
        name: 'Gap Analysis',
        description: 'Identify redundancy gaps',
        status: 'not started',
        deadline: '2024-09-30',
        weight: 30,
        percentCompleted: 0,
        files: [],
      },
      {
        id: 't42',
        name: 'Implementation Plan',
        description: 'Develop improvement plan',
        status: 'not started',
        deadline: '2024-12-15',
        weight: 30,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
  {
    id: '15',
    processNumber: 'PI-015',
    name: 'Substation Automation',
    description: 'Automate substation operations and monitoring',
    status: 'in progress',
    completenessRate: 62,
    startDate: '2023-10-01',
    completionDate: '2024-06-30',
    tasks: [
      {
        id: 't43',
        name: 'Equipment Selection',
        description: 'Select automation equipment',
        status: 'completed',
        deadline: '2024-01-31',
        weight: 30,
        percentCompleted: 100,
        files: [],
      },
      {
        id: 't44',
        name: 'Installation',
        description: 'Install automation systems',
        status: 'in progress',
        deadline: '2024-05-31',
        weight: 50,
        percentCompleted: 60,
        files: [],
      },
      {
        id: 't45',
        name: 'Testing & Commissioning',
        description: 'Test and commission systems',
        status: 'not started',
        deadline: '2024-06-30',
        weight: 20,
        percentCompleted: 0,
        files: [],
      },
    ],
  },
];
